### PR TITLE
Added web support

### PR DESCRIPTION
**Pull request by MoacirSchmidt**
See https://github.com/MoacirSchmidt/flutter_cached_network_image#web-support

"CachedNetworkImageProvider" was NOT ported! (still works in mobile, of course)

### CODE REVIEW

**Comment by eopeter** [comment]
Can this be promoted?

**Comment by phimath** [comment]
This is working on web, thank you!  The fade in animations are not working however.  They do work on web when using FadeInImage.memoryNetwork, but would also like the caching.

**Comment by juanagu** [comment]
Hi @renefloor, could you review this PR? Thanks!

**Comment by renefloor** [comment]
@juanagu Thanks for the effort of this PR.
However, this is not the way I want to have it implemented. Simply said it is:
```
if(web)
  networkImage
else
  CachedNetworkImage
```
I want to make the cachemanager web compatible by not using sqflite anymore. It will be a bit more effort, but it will be a better solution in the long term. For example, this solution wouldn't work on MacOS as well.

**Comment by juanagu** [comment]
Ok! thanks @renefloor

**Pull request closed without merging**
