### PR TITLE
Fixed: Deprecated API usage 

### PR DESCRIPTION
**Pull request by muhib349**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Removed deprecated method `webOnlyInstantiateImageCodecFromUrl`, used `createImageCodecFromUrl`

### :arrow_heading_down: What is the current behavior?
Warning, about to remove `webOnlyInstantiateImageCodecFromUrl` method

### :new: What is the new behavior (if this is a feature change)?
Replaced with `createImageCodecFromUrl`

### :boom: Does this PR introduce a breaking change?
No
### :bug: Recommendations for testing
Yes

### :memo: Links to relevant issues/docs
#906 

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Review by amrgetment — APPROVED** [review]

**Review by amorenew — APPROVED** [review]

**Comment by erdzan12** [comment]
Are there any further points which need to be clarified to merge this?

**Comment by amrgetment** [comment]
@erdzan12 I am not a repo contributor but I can approve only 😂

**Comment by muhib349** [comment]
> Are there any further points which need to be clarified to merge this?

No, that's the only thing.

**Comment by ReinisSprogis** [comment]
Would be nice to see this progressing. Any way I can help?

**Comment by ReinisSprogis** [comment]
> > Are there any further points which need to be clarified to merge this?
> 
> No, that's the only thing.

Any idea why this is not progressing?

**Comment by amrgetment** [comment]
@renefloor Could you check this PR? Thanks

**Comment by MyBlueford16** [comment]
any update on this?

**Comment by nc-jeni** [comment]
+1

When will this be merged and released in a new version?
@amorenew  @amrgetment

**Comment by mgrv-yhlee** [comment]
100016_93b60be0-5a2b-43b7-bd7e-3557acc1ed30

**Comment by c-seeger** [comment]
@renefloor @amorenew any chance this project gets some love?

**Comment by ReinisSprogis** [comment]
Package is abandoned.

**Comment by amrgetment** [comment]
@amorenew @amrgetment is not a maintainer I just tried to approve but as both accounts are not a collaborator then it won’t affect the PR

**Comment by chief-nerd** [comment]
We need this merged ... fix is simple and no risk. Needs to go in!

**Comment by c-seeger** [comment]
@BeMacized or @martijn00 since this repository is part of Baseflow, can you help out here?

**Comment by chief-nerd** [comment]
Ok awesome -- we have 2 reviews here! --- No we "just" need to press the "Merge" button and make a release .... Anyone?

**Comment by amrgetment** [comment]
@mvanbeusekom we need a review and merge for this PR

**Comment by ReinisSprogis** [comment]
I suggest to use this package instead. https://pub.dev/packages/extended_image

**Comment by nc-jeni** [comment]
> LGTM!

Please tell, which stable release version that will have this fix included?
@mvanbeusekom

**Comment by mvanbeusekom** [comment]
It has been released in version 1.2.0 of the cached_network_image_web package.

This as a dependency of the cached_network_image, so running `flutter pub upgrade` should automatically download the new version.

**Comment by c-seeger** [comment]
@mvanbeusekom this looks wrong to me since the current version released is v3.3.1 which is from december 31, 2023.

I guess the correct tag version would be
v3.3.2

Also the v1.2.0 tag is named chached_network_image_web_v1.2.0 which is not a valid semversion

**Comment by mvanbeusekom** [comment]
Hi @c-seeger,

The [cached_network_image](https://pub.dev/packages/cached_network_image) package internally relies on the [cached_network_image_web](https://pub.dev/packages/cached_network_image_web) package to provide support for the web platform. 

If you check the [pubspec.yaml](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/cached_network_image/pubspec.yaml) of the [cached_network_image](https://pub.dev/packages/cached_network_image) package you'll see the following dependency:
```yaml
dependencies:
  ...
  cached_network_image_web: ^1.1.1
```

The `^` syntax here is a version constraint meaning: "depend on the latest version of `cached_network_image_web` larger or equal to 1.1.1 but smaller then 2.0.0. This means that version 1.2.0 of the cached_network_image_web will automatically be used if you update your dependencies. More details on dependencies and version constraints can be found in the Dart documentation: https://dart.dev/tools/pub/dependencies#version-constraints.

Regarding the tag, this is just a tag and since the repository contains multiple packages we need to differentiate between which version of which package is updated, hence the name of the package in front of the version number in the tag name. If you want to know more of how this works exactly read up on the [Federated architecture](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins) on the Flutter documentation.

**Comment by c-seeger** [comment]
> Hi @c-seeger,
> 
> The [cached_network_image](https://pub.dev/packages/cached_network_image) package (current version 3.3.1) internally relies on the [cached_network_image_web](https://pub.dev/packages/cached_network_image_web) package (current version 1.2.0) to provide support for the web platform.
> 
> If you check the [pubspec.yaml](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/cached_network_image/pubspec.yaml) of the [cached_network_image](https://pub.dev/packages/cached_network_image) package you'll see the following dependency:
> 
> ```yaml
> dependencies:
>   ...
>   cached_network_image_web: ^1.1.1
> ```
> 
> The `^` syntax here is a version constraint meaning: "depend on the latest version of `cached_network_image_web` larger or equal to 1.1.1 but smaller then 2.0.0. This means that version 1.2.0 of the cached_network_image_web will automatically be used if you update your dependencies. More details on dependencies and version constraints can be found in the Dart documentation: https://dart.dev/tools/pub/dependencies#version-constraints.
> 
> Regarding the tag, this is just a tag and since the repository contains multiple packages we need to differentiate between which version of which package is updated, hence the name of the package in front of the version number in the tag name. If you want to know more of how this works exactly read up on the [Federated architecture](https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins) on the Flutter documentation.

Awesome thank you for clarifying this :+1:

**Pull request merged**
