### PR TITLE
Catch codec error

### PR DESCRIPTION
**Pull request by miyakeryo**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
Error widget not shown when invalid content. #320
For example, when redirected to a not found page, but http status was 200.

### :new: What is the new behavior (if this is a feature change)?
Error widget shown when invalid content.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Open normal html url

### :memo: Links to relevant issues/docs
https://github.com/Baseflow/flutter_cached_network_image/issues/320

### :thinking: Checklist before submitting

- [x] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/BaseflowIT/flutter-geolocator/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by renefloor** [comment]
Thanks! It looks nice. I think it would even be better if the placeholder isn't removed until the image is pre-loaded. In your solution the transition image is shown before the image is loaded or failed loading. We could just build the placeholder like this, but than the fade animation already starts:

(simplified)
```      builder: (c, snapshot) {
        if (snapshot.hasError) {
          return _errorWidget(c, snapshot.error);
        } else if (snapshot.hasData){
          return widget.imageBuilder(c, imageProvider)
        } else {
          return widget.placeholder(context, widget.imageUrl)
      },```

**Comment by miyakeryo** [comment]
I've changed it to preload as soon as file is loaded. The placeholder is displayed until the preload is complete.

**Comment by renefloor** [comment]
```
_cacheManager()
        .getFile(widget.imageUrl, headers: widget.httpHeaders)
```
The .getFile method is a stream, because it first returns a file from the cache and if it is outdated it will return the updated file from the server. Now you made it into a Future and only take the first result it returns, which means it loses functionality.

**Comment by miyakeryo** [comment]
How can I test it?
I did as below at first, but when called again during await, there was a bug.
Next, I will change CacheManager.getFile().
```dart
_cacheManager()
        .getFile(widget.imageUrl, headers: widget.httpHeaders)
        // ignore errors if not mounted
        .handleError(() {}, test: (_) => !mounted)
        .where((f) => f?.originalUrl != fromMemory?.originalUrl || f?.validTill != fromMemory?.validTill)
        .asyncMap((fileInfo) async {
          if (fileInfo != null) {
            final completer = Completer<void>();
            await precacheImage(
              FileImage(fileInfo.file),
              context,
              size: widget.width != null && widget.height != null ?
              Size(widget.width, widget.height) : null,
              onError: completer.completeError,
            );
            if (!completer.isCompleted) completer.complete();
            await completer.future;
          }
          return fileInfo;
        })
```

**Comment by miyakeryo** [comment]
I solved it!

**Comment by renefloor** [comment]
Hi @miyakeryo ,

Just about this week I came across [this lecture](http://www.cs.cmu.edu/~bam/uicourse/830spring20/05-830-2020-03-23-Lecture-10-Flutter.mp4) (via [Reddit](https://www.reddit.com/r/FlutterDev/comments/fu2urf/lecture_about_flutter_hans_muller_and_dan_field/)).

At about 1:12:00 Dan Field talks about the effects of image pre-caching on memory. The short version is that Flutter does a great job at only having those images in memory that are shown on the screen. If you start pre-caching the images you could easily crash your app by overflowing the memory, especially if you have a list with 1000s of images. I still have to dig deeper into this topic, but I'm afraid your PR does exactly that. When you just show 1 or 2 images that will be fine, but this library is also used by people that load 1000s of images.

**Comment by miyakeryo** [comment]
It's not going well :thinking:

**Comment by renefloor** [comment]
I'm sorry, life is not always easy

**Comment by miyakeryo** [comment]
I checked it with [Memory tool](https://flutter.dev/docs/development/tools/devtools/memory). Actually there is no difference between pre-caching or not.

| precache |
| --- |
| Screen Shot 2020-04-08 at 15 01 25 |

| no precache |
| --- |
| Screen Shot 2020-04-08 at 15 05 01 |


The test code is bellow.

```dart
// main.dart

Widget _content(int page) {
  switch (currentPage) {
    case 2:
      return _gridView();
    default:
      return const SizedBox();
  }
}

final _scrollController = ScrollController();

Future _autoScroll() async {
  final position = _scrollController.position;
  if (position.pixels >= position.maxScrollExtent) {
    return;
  }
  await position.animateTo(
    position.pixels + 10,
    duration: const Duration(milliseconds: 10),
    curve: Curves.linear,
  );
  return _autoScroll();
}

Widget _gridView() {
  if (!_scrollController.hasClients) {
    Future.delayed(const Duration(milliseconds: 100), _autoScroll);
  }
  return GridView.builder(
    controller: _scrollController,
    itemCount: 1200, // 😄 many enough
    gridDelegate:
      const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 6),
    itemBuilder: (BuildContext context, int index) => CachedNetworkImage(
      imageUrl: 'https://loremflickr.com/100/100/music?lock=$index',
      placeholder: _loader,
      errorWidget: _error,
      usePrecache: true, // 🚗 true or false
    ),
  );
}
```

**Comment by miyakeryo** [comment]
Hi @renefloor 
How do you think  about https://github.com/Baseflow/flutter_cached_network_image/pull/359#issuecomment-610769730 ?
I think it's good.

**Comment by renefloor** [comment]
@miyakeryo I'm currently also working on another solution. 
I'm changing the ImageProvider to handle the loading, progress and the errors as you can see in this commit: https://github.com/Baseflow/flutter_cached_network_image/commit/eabee04ef67029c12d7317a7dc4810d23a4b6926

In this way all the errors are handled in 1 place and there is no need to forcefully pre-load the image into the cache.

**Comment by miyakeryo** [comment]
That's an interesting solution.
Ok, It's your product.

**Pull request closed without merging**
