### PR TITLE
Fix analyzer issues and update example for Dart 3

### PR DESCRIPTION
**Pull request by Carapacik**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Update to support newest Dart version(3.0.0)
Update example
Fix analyzer issues
Add ErrorListener to CacheNetworkImage widget 

#843
#849 
#850 
#853 
#854 
#855 
Checklist before submitting

- [X] All projects build
- [X] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [X] Relevant documentation was updated
- [X] Rebased onto current develop

Use this temp solution:
```yaml
  cached_network_image:
    git:
      url: https://github.com/Carapacik/flutter_cached_network_image.git
      path: cached_network_image
```

### CODE REVIEW

**Comment by BirjuVachhani** [comment]
Any update on this? This is a blocker for me!

**Comment by Carapacik** [comment]
Temp solution:
```yaml
  cached_network_image:
    git:
      url: https://github.com/Carapacik/flutter_cached_network_image.git
      path: cached_network_image
      ref: actual
```

**Comment by gabielchong** [comment]
Any update on this? This is a blocker for me also.

**Comment by ibraheemalayan** [comment]
Having the same issue, are there any updates ?

**Comment by ibraheemalayan** [comment]
Having the same issue, are there any updates ?

@renefloor

**Comment by MarlonJD** [comment]
It should be approve ASAP!

**Comment by Carapacik** [comment]
Also I think there will need to be an update for flutter 3.7:
```
DecoderBufferCallback' is deprecated and shouldn't be used. Use ImageDecoderCallback with ImageProvider.loadImage instead. This feature was deprecated after v3.7.0-1.4.pre
```

**Comment by Carapacik** [comment]
@renefloor  Also I think there will need to be an update for flutter 3.10(Dart 3) in next version:
```
`DecoderBufferCallback' is deprecated and shouldn't be used. 
Use ImageDecoderCallback with ImageProvider.loadImage instead. This feature was deprecated after v3.7.0-1.4.pre
```

**Comment by Carapacik** [comment]
#843 
#849 
#850 
#853 
#854 
#855

**Comment by Carapacik** [comment]
@renefloor
There will need to be an update for flutter 3.10(Dart 3) in next version:
```
`DecoderBufferCallback' is deprecated and shouldn't be used. 
Use ImageDecoderCallback with ImageProvider.loadImage instead. This feature was deprecated after v3.7.0-1.4.pre
```

**Comment by renefloor** [comment]
Hi @Carapacik Thanks for the effort on the PR. However, this PR is really big, making it hard to review as it's unclear why some changes are made. Would it be possible to split this in smaller PR's with separate goals. As far as I know this package is fully compatible with Flutter 3.10 after we released your fixes in flutter_cache_manager.

Thanks for the warning that `DecoderBufferCallback` is now deprecated. I searched for the PR which did that and see it's about ResizePolicy. That's something I want to take a look into to see if we actually should support that with the image resizing in the cache package as well: https://github.com/flutter/flutter/pull/121154

**Comment by Carapacik** [comment]
@renefloor I can break this PR into 2 parts: analyzer and example update and deprecate DecoderBufferCallback

**Comment by renefloor** [comment]
That would be great!

**Comment by Carapacik** [comment]
Complete

**Comment by Carapacik** [comment]
Update example and specify types

**Comment by Carapacik** [comment]
I am ready to add another PR with other changes related to deprecated DecoderBufferCallback.

**Comment by erdnj** [comment]
I think this pr should be merged immediately .

**Pull request closed without merging**
