### PR TITLE
Fix #503 - migration to dart 2.12 with null safety

### LINKED ISSUE #503: Support NNBD
## 🐛 Bug Report

Currently using Non Nullable for flutter, all other dependencies work fine except for cached_network_image. Now I'm getting a long list of errors and the app cannot run nor build.

Here is the long list of errors I'm getting:
`
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/compat.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/compat.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:5:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/compat.dart' show SqfliteOptions;
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/constant.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/constant.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/utils.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/utils.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/utils/utils.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/utils/utils.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqlite_api.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/sqlite_api.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:18:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/factory_mixin.dart'
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:8:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/database.dart' // ignore: implementation_imports
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:12:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/database_mixin.dart' // ignore: implementation_imports
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:16:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/exception.dart'
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:20:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/factory.dart' show SqfliteDatabaseFactory;
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:21:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/mixin/constant.dart'
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_import.dart:32:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/mixin/factory.dart'
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sql_builder.dart:1:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite_common/src/sql_builder.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:13:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite/src/compat.dart';
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:16:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'sqlite_api.dart';

../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sql.dart:5:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite/src/sql_builder.dart'
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:12:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:sqflite/sql.dart' show ConflictAlgorithm;
^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:70:17: Error: Optional parameter 'duration' should have a default value because its type 'Duration' doesn't allow null.
 - 'Duration' is from 'dart:core'.
      {Duration duration, void Function() callback}) {
                ^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:70:43: Error: Optional parameter 'callback' should have a default value because its type 'void Function()' doesn't allow null.
      {Duration duration, void Function() callback}) {
                                          ^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:128:10: Error: Optional parameter 'version' should have a default value because its type 'int' doesn't allow null.
    {int version,
         ^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:129:27: Error: Optional parameter 'onConfigure' should have a default value because its type 'FutureOr<void> Function(Database)' doesn't allow null.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
    OnDatabaseConfigureFn onConfigure,
                          ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:130:24: Error: Optional parameter 'onCreate' should have a default value because its type 'FutureOr<void> Function(Database, int)' doesn't allow null.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
    OnDatabaseCreateFn onCreate,
                       ^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:131:31: Error: Optional parameter 'onUpgrade' should have a default value because its type 'FutureOr<void> Function(Database, int, int)' doesn't allow null.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
    OnDatabaseVersionChangeFn onUpgrade,
                              ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:132:31: Error: Optional parameter 'onDowngrade' should have a default value because its type 'FutureOr<void> Function(Database, int, int)' doesn't allow null.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
    OnDatabaseVersionChangeFn onDowngrade,
                              ^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/sqflite.dart:133:22: Error: Optional parameter 'onOpen' should have a default value because its type 'FutureOr<void> Function(Database)' doesn't allow null.
 - 'Database' is from 'package:sqflite_common/sqlite_api.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/sqlite_api.dart').
    OnDatabaseOpenFn onOpen,
                     ^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/factory_impl.dart:10:24: Error: Field '_databaseFactory' should be initialized because its type 'SqfliteDatabaseFactory' doesn't allow null.
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
SqfliteDatabaseFactory _databaseFactory;
                       ^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/factory_impl.dart:42:30: Error: The value 'null' can't be assigned to a variable of type 'SqfliteDatabaseFactory' because 'SqfliteDatabaseFactory' is not nullable.
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
    sqfliteDatabaseFactory = null;

../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/factory_impl.dart:53:5: Warning: Operand of null-aware operation '??=' has type 'SqfliteDatabaseFactory' which excludes null.
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
    _databaseFactory ??= SqfliteDatabaseFactoryImpl();
    ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/factory_impl.dart:67:5: Warning: Operand of null-aware operation '??=' has type 'SqfliteDatabaseFactory' which excludes null.
 - 'SqfliteDatabaseFactory' is from 'package:sqflite_common/src/factory.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite_common-1.0.2+1/lib/src/factory.dart').
    _databaseFactory ??= SqfliteDatabaseFactoryImpl();
    ^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+1/lib/src/sqflite_impl.dart:17:13: Error: A value of type 'Future<T?>' can't be returned from a function with return type 'Future<T>' because 'T?' is nullable and 'T' isn't.
 - 'Future' is from 'dart:async'.
    channel.invokeMethod<T>(method, arguments);

FAILURE: Build failed with an exception.

* Where:
Script '/../flutter_tools/gradle/flutter.gradle' line: 900

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command '/../flutter/bin/flutter'' finished with non-zero exit value 1
`

### Expected behavior
App should run without errors like it did prior to making the non nullable change.

### Reproduction steps
In pubspec.yaml:
`environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
cached_network_image: ^2.3.3`

Added analysis_options.yaml:
`analyzer:
  enable-experiment:
    - non-nullable`

In my launch.json for VS code, I added the args
`        "--enable-experiment=non-nullable",
        "--no-sound-null-safety",`

### Configuration
**Version:** 1.x
Version 2.3.3

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

### PR DESCRIPTION
**Pull request by bartektartanus**
### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by renefloor** [comment]
@bartektartanus I would like to make some changes to reduce the number of `!`s. Is it OK for you if I just push code to this PR?

**Comment by bartektartanus** [comment]
Of course you can make changes in this PR. I've added the ! In places where fields where used in null-unsafe way ;) so if you know how to change this to better behavior - please do it. 

About the test - mockito had some breaking changes and I'm afraid that some of the tests needs to be rewritten - not just fixed. :(

**Comment by renefloor** [comment]
> Of course you can make changes in this PR. I've added the ! In places where fields where used in null-unsafe way ;) so if you know how to change this to better behavior - please do it.

Yes I know, for example here I think we can supply it in the function, because where we call it we know it is not null:
```
  Widget _octoPlaceholderBuilder(BuildContext context, PlaceholderWidgetBuilder placeholder) {
    return placeholder(context, imageUrl);
  }
```

> About the test - mockito had some breaking changes and I'm afraid that some of the tests needs to be rewritten - not just fixed. :(

Yes it is horrible, but not fixing or rewriting the test will drop the coverage to almost 0 😢 
I'll give it a try as well though :)

**Comment by bartektartanus** [comment]
> Edit2: I have troubles creating the mocks with the build_runner...
> 
> ```
> ➜  flutter_cached_network_image git:(nnbd) ✗ pub run build_runner
> Could not find a file named "pubspec.yaml" in "/Users/renefloor/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-17.0.0".
> ```

Maybe clear the cache? Using repair command: https://dart.dev/tools/pub/cmd/pub-cache
or just remove `_fe_analyzer_shared` directory.

**Comment by renefloor** [comment]
I think I'm going the way of #554, as that feels more promising than fixing the bugs of mockito. I'll publish a pre-release while we fix the tests.

**Comment by renefloor** [comment]
image
🎉

**Comment by diegotori** [comment]
@renefloor any progress on this, since this is one of the very few libraries remaining in my app that doesn't have a full Null-Safety release. Thanks in advance.

**Comment by renefloor** [comment]
Yes, this https://github.com/Baseflow/octo_image/issues/17 was the last real issue before I could make it stable.

**Pull request merged**
