### PR TITLE
Wrap imageBuilder's output with KeyedSubtree, prevent flicker

### PR DESCRIPTION
**Pull request by MichaelMarner**
Both the latest version on `master` and `develop` have an issue where the image flickers after loading. I believe these issues are all the same:

#274, #258, #253 

@cbenhagen mentioned in a [comment](https://github.com/renefloor/flutter_cached_network_image/issues/258#issuecomment-545888343) that reverting 3d71ad007c0737f5dbdb8206747b264ba84407f1 fixes the issue. I've dug a bit further and isolated the issue to the single call to `setState()`.

Removing the call to setState causes the problem to go away, because there is no additional rebuild after the animation has completed. However, without the call to setState the placeholder will always be rendered under the loaded image, which is unnecessary work.

[Further investigation](https://github.com/renefloor/flutter_cached_network_image/pull/289#issuecomment-561632223) shows that the underlying cause is when `imageBuilder` is called any existing state is cleared. Most obviously, CircleAvatar uses an AnimatedContainer to render the background image as a decoration. The subsequent call to `imageBuilder` causes that AnimatedContainer to re-animate, which appears as a flicker.

This PR fixes the issue by wrapping the widget returned by `imageBuilder` in a KeyedSubtree. The key specified is based on the image path, so if the path changes the image should be re-rendered correctly. I have also added another image to the example app demonstrating use with CircleAvatar. The flicker can be seen by running this new example app with the existing package, and also verifies the fix working correctly.

### CODE REVIEW

**Comment by pilotviper134** [comment]
Any ideas?

**Comment by cbenhagen** [comment]
@Kavantix what do you think?

**Comment by Kavantix** [comment]
Can you supply a small example which illustrates the problem?

The setState is there such that the placeholder will be removed when the animation is done so that needs to stay.
But I’m curious to see what is causing this I have not seen it happen yet.

**Comment by MichaelMarner** [comment]
Hi @Kavantix 

Thanks for the clarification, as it helped me figure out what is going on and why this isn't consistently a problem for everyone. 

First up, a minimal demonstration of the problem, just a simplified version of this repo's example app:

https://gist.github.com/MichaelMarner/f4de125ba46356ea362bdf53f8e3b980

In this example, the image fades in like normal, and then flashes gone and back again. This flash is triggered by the call to setState, which in turn triggers a rebuild of the widget.

The issue _only_ appears when using the `imageBuilder` functionality, and also only when using the imageProvider in a particular way. In short, the culprit is not really with this package, but with various Flutter widgets that use [AnimatedContainer](https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html).

AnimatedContainer automatically animates changes to properties, including Decoration. Under the hood [CircleAvatar](https://github.com/flutter/flutter/blob/1aedbb1835/packages/flutter/lib/src/material/circle_avatar.dart#L192) and other built in widgets apply images as part of the container's decoration. When setState triggers a rebuild, AnimatedContainer is rebuilt within CircleWidget, which does its own short animation of the Decoration.

In my testing, the fix for this is to ensure whatever `imageBuilder` returns has a `key` applied:

```dart
                return CircleAvatar(
                  key: Key('my key),
                  backgroundImage: provider,
                  radius: 200,
                )
```

So that the state is maintained through the rebuilds.

So I think the right thing to do here is to document this behaviour in the README, rather than modify this package. I'm happy to do this tomorrow, and will update this PR.

I guess this has come up so often because remote avatars, and therefore CircleAvatar, is such a common use for this package.

Cheers!

**Comment by Kavantix** [comment]
@MichaelMarner that makes a lot of sense.
But only changing the docs is not enough I think.
We should probably just wrap the result of the imageBuilder inside a KeyedSubtree

**Comment by MichaelMarner** [comment]
Have made the change to wrap `imageBuilder`'s output in a KeyedSubtree, and updated this PR's description. Have verified this change fixes the issue when used with CircleAvatar and other widgets containing animations.

**Comment by diego-lipinski-de-castro** [comment]
I tried @MichaelMarner branch and it was flickering still, do we need to change something in the implementation?

**Comment by Kavantix** [comment]
@diego-lipinski-de-castro can you share an example which still flickers on that branch?

**Comment by diego-lipinski-de-castro** [comment]
Cant share full code of the application because company but this is what I can do https://pastebin.com/jLKDb0qk, the image it loads is around 1mb (1024x768px (not sure but around this))

**Comment by MichaelMarner** [comment]
This PR probably won't affect flicker issues caused by `ListView.builder`. 

This PR keys the result of `imageBuilder`, but if ListView's `itemBuilder` decides to rebuild a row in the list, that may create an entirely new CachedNetworkImage object with new state, and will therefore show the initial image fade in animation again. A video would confirm this is what is happening, and can easily be fixed by adding a `key` to whatever widget your `itemBuilder` returns.

**Comment by diego-lipinski-de-castro** [comment]
WhatsApp Video 2019-12-05 at 20 15 18

This gif shows a bit which it doesnt look that bad, but sometimes it is really annoying, i have tried to  put a UniqueKey in the container or the CachedNetwork widget but doesnt seem to work, is there any other recomendation to use it within ListViews?

**Comment by MichaelMarner** [comment]
I have added `ListView.builder` and `GridView.builder` views to the example app. Unfortunately I have not been able to replicate this issue. @diego-lipinski-de-castro I know you aren't able to share your exact code, but if you could re-create a minimal working example of the problem (maybe modify the example app), I can look into it further.

**Comment by diego-lipinski-de-castro** [comment]
I will try to recreate it in a smaller app, which version of the lib you used on the video?

**Comment by MichaelMarner** [comment]
@diego-lipinski-de-castro you can install my branch. In your pubspec.yml:

```yaml
cached_network_image:
  git: https://github.com/MichaelMarner/flutter_cached_network_image.git
  ref: stop-flicker
```

**Comment by rtlsilva** [comment]
I ran into this issue, and following this issue's findings, I tried adding a `Key` based on the image path to my `CircleAvatar` without success.  

In my specific case, the image path was always the same. What _did_ work was adding `key: UniqueKey()` to the `CircleAvatar`.
Not sure if this is recommended, correct or useful, but that's what worked for me so I wanted to share it here.

**Comment by renefloor** [comment]
> I will try to recreate it in a smaller app, which version of the lib you used on the video?

@diego-lipinski-de-castro Did you try to recreate the issue with this solution?

**Pull request merged**
