### PR TITLE
Switch to use mocktail

### PR DESCRIPTION
**Pull request by daohoangson**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Switch from `mockito` to `mocktail`. This should help with the NNBD effort at #550 

### :arrow_heading_down: What is the current behavior?

We are using `mockito`.

### :new: What is the new behavior (if this is a feature change)?

Switch to a different package with a similar api.

### :boom: Does this PR introduce a breaking change?

No.

### :bug: Recommendations for testing

Not that I know of.

### :memo: Links to relevant issues/docs

There is a bug with the `mocktail` package, I'm submitting a PR to fix it https://github.com/felangel/mocktail/pull/18. For reviewing purposes, let's do it with a temporary git dependency.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by bartektartanus** [comment]
Looks promising - build passed, tests are green. @renefloor what do you think?

**Comment by renefloor** [comment]
Looks good to me idd, but I cannot publish this with a git reference, so I'm hesitant merging this before the PR felangel/mocktail#18 is merged.

**Comment by daohoangson** [comment]
Yes, we need to wait for the new release of `mocktail`. I'll update this PR once it's available.

**Comment by felangel** [comment]
Just published [v0.0.1-dev.12](https://pub.dev/packages/mocktail) 🎉 
Thanks again @daohoangson for the contribution 💯

**Comment by daohoangson** [comment]
Thanks @felangel for the merge! Let's wait for CI...

**Comment by daohoangson** [comment]
It's working! @renefloor @bartektartanus please take a look.

**Comment by renefloor** [comment]
LGTM!

**Pull request merged**
