### PR TITLE
Bug fix: Fix errorWidget on dart DDC (web)

### PR DESCRIPTION
**Pull request by JustusFluegel**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug fix: The errorWidget would never be displayed when running using DDC (dart web) and the HttpGet option, which happens because the catch block currently never gets executed when using streams with `await for` on dart DDC.
As such this pr refactors the file to use a StreamController instead, re-implementing the original behavior.

### :arrow_heading_down: What is the current behavior?

Placeholder stays displayed even if a error response (e.g. 404) happened, when running using DDC

### :boom: Does this PR introduce a breaking change?

No, this is a pure bug fix.

### :bug: Recommendations for testing

Maybe add a DDC test suite? idk

### :memo: Links to relevant issues/docs

-  https://github.com/dart-lang/sdk/issues/47764

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by mitcoef** [comment]
I agree with this change. Even if the mentioned issue is fixed in the future, using the `Stream` class `listen` method is much more idiomatic and should thus be preferred regardless.

**Comment by martijn00** [comment]
@JustusFluegel can you fix the unit tests for this?

**Comment by JustusFluegel** [comment]
Will do that in the next few days, don't have the time to look at it right now :) Thanks for finally taking a look at this tho, appreciate you taking the time

**Comment by JustusFluegel** [comment]
So I've added a try catch which mirrors the old behavior of sending the `UnimplementedError` of trying to create the stream  from the mock cache controller across the output stream as well - I don't know if this is the prettiest solution but it should be the one that mirrors the old code the closest. If you wish to do this in a different way, let me know :)

**Pull request merged**
